name: danleo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  google_maps_flutter: ^2.5.0
  geolocator: ^11.0.0
  http: ^0.13.6
  firebase_auth: ^5.5.4
  firebase_storage: ^11.6.6
  image_picker: ^1.1.2
  image: ^4.5.4
  intl: ^0.20.2
  country_picker: ^2.0.20
  flutter_launcher_icons: ^0.14.4
  flutter_admin_scaffold: 1.4.0
  sensors_plus: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"